### ISSUE TITLE
paste_img_and_link() generates empty files for images (.png)

### ISSUE THREAD

**Issue by quesada** [renerocksai/telekasten.nvim#131] opened 2022-05-12 22:02 UTC
**Please confirm**
- [ x] I am running the latest version of this plugin

**Tell us about what's bothering you...**
Pasting images with the function  

`lua require('telekasten').paste_img_and_link()<CR>`
Produces an empty png that is not viewable with any img viewing tool I tried (on linux). File size is 1B so that hints at the image not being done correctly. I took the screenshot with spectacle (KDE).

**Comment by lambtho12** [comment] 2022-05-13 06:52
Probably related to #132. Can you try setting up the `image_subdir` correctly and then verify if this bug persists?

**Comment by lambtho12** [comment] 2022-05-18 12:31
I can confirm. The problem seems to be with `xclip`. When I run the command manually
```bash
xclip -selection clipboard -t image/png -o > /home/lambtho12/Zettel/img/pasted_img_20220518142832.png
```
it returns
```bash
Error: target image/png not available
```
and creates the a 0 KB file with the proper name.

**Comment by Cruising0904** [comment] 2022-08-31 06:58
can I use this function with wl-copy running on wayfire

**Comment by lambtho12** [comment] 2022-08-31 08:16
> can I use this function with wl-copy running on wayfire

Currently this function looks for `xclip` or `osascript` and returns an error if none of these is found (see below). 

So my guess is that it is not possible. That being said, it should not be very hard to add support for `wl-copy`. If you  can make a PR for that, I will happily review it and merge asap.

https://github.com/renerocksai/telekasten.nvim/blob/fdb089daf6d66e9d559645e664a172ff5b6a5ddd/lua/telekasten.lua#L404-L424

**Comment by lambtho12** [comment] 2023-05-01 18:43
Ok, so I looked into it a bit more and I think I have found the issue...
It all eventually goes down to `how` did you first copy the image. Apparently, some programs do not store the image normally in the clipboard for some reason. Therefore xclip cannot see them and cannot paste them. 

On my system, if I do a simple `crtl-c` in my file manager (Thunar), I cannot repaste it using xclip. However, if I just open firefox, right click and `copy image`, I can then copy the image properly using xclip. In the first senario, I end up with an empty file with Telekasten as OP here. In the second, it all works fine.

I do not think it is something that can be fixed by Telekasten though. You can simulate the same test by simply copying the image like you always do, open Gimp and paste it there. If Gimp does not see the image either, than I think we can confirm the issue is more with xclip and the way clipboard is managed in general and not Telekasten. 

@quesada , I know it has been a long time, but could you just verify, so we can close this issue (unfortunately without providing a fix).

**Comment by Vaisakhkm2625** [comment] 2023-05-02 01:52
0B picture is generated by redirection symbol

``` bash
wl-paste -n -t image/png >  hi.png
```
[here](https://github.com/renerocksai/telekasten.nvim/blob/2efa3a51ff5bb716bbaae53fd025042a41ea4fde/lua/telekasten.lua#L353)

in this, hi.png will be generated even if `wl-paste -n -t image/png` doesn't generated a value and prints `No suitable type of content copied`,(or gives error in nvim)

normally we prevent this like this, 
```
image=$(wl-paste -n -t image/png) && echo "$image" > hi.png
```
but shell will messup the bytes.....

 so better to delete after making it and checking if it failed
```
wl-paste -n -t image/png > outfile.png || rm -f outfile.png
```
but this method will return always `true`, and [this](https://github.com/renerocksai/telekasten.nvim/blob/2efa3a51ff5bb716bbaae53fd025042a41ea4fde/lua/telekasten.lua#L409) error message will not be shown

**Comment by lambtho12** [comment] 2023-05-02 10:32
@Vaisakhkm2625 , apparently, the simple `if not result` was not working if `result` was an actual error code (`256` in my case). So I added and `or` statement. Can you check if it still works?

**Comment by Vaisakhkm2625** [comment] 2023-05-08 10:38
> Ok, I fixed the fix by getting rid of `os.execute` altogether. Something that I should have done straight away anyway... I took the opportunity to add #242 as a reminder to fix this everywhere so it does not cause more issues down the line.

it seems it's still making 0B images...
![image](https://user-images.githubusercontent.com/68694876/236802985-2c769220-535a-4d17-b461-fa9b62cdacaa.png)

possibly a path error while removing?...  notice there is '//' in the error message....
```
/home/vaisakh/vaisakhRoot/notes/img//pasted_img_2023050
8160529.png 
```

**Comment by lambtho12** [comment] 2023-05-08 11:09
Ok. I will have a look tonight. Thank you

**Comment by lambtho12** [comment] 2023-05-09 08:06
Fixed with https://github.com/renerocksai/telekasten.nvim/commit/53f66656772e03da3d79b09b1ffa49b64772fe2f

This took longer than expected. There is definitely a need to refactor all path handling using Plenary :laughing:

**Closed by lambtho12** 2023-05-09 08:06 UTC
Labels: bug, wontfix
