### ISSUE TITLE
[BUG] Renaming a file keeps the old file and creates another file with a new name

### ISSUE THREAD

**Issue by dmytrodubinin** [renerocksai/telekasten.nvim#114] opened 2022-04-27 16:03 UTC
**Please confirm**
- [ ] I am running the latest version of this plugin

**Describe the bug**
When I rename file I get an error and have 2 files: old and new with new name
![image](https://user-images.githubusercontent.com/8066458/165560466-c23cccd6-9416-43c3-98e8-d9211a342139.png)
![image](https://user-images.githubusercontent.com/8066458/165561312-69849684-8591-4471-943b-bf0a3657b33d.png)

**To Reproduce**
1. Start nvim
2. Try to rename file
3. Get an error and two files width old name and new name

```
E5108: Error executing lua ...cal/share/nvimvimplug/telekasten.nvim/lua/telekasten.lua:
1652: Vim(bdelete):E94: No matching buffer for Fromm.md
stack traceback:
        [C]: in function 'cmd'
        ...cal/share/nvimvimplug/telekasten.nvim/lua/telekasten.lua:1652: in function '
rename_note'
        [string ":lua"]:1: in main chunk
```

**Expected behavior**

**Operating system (please complete the following information):**
 - OS: Fedora 35

**Additional context**

**Comment by lambtho12** [comment] 2022-04-27 18:21
Just made some tests. It looks like the issue is with filenames with a space in it. Don't do that :smile: 

Fixing that now...

**Comment by lambtho12** [comment] 2022-04-27 18:29
Closed by https://github.com/renerocksai/telekasten.nvim/commit/7f5b625e4ffc5dea570835396a02e775e59ff0e2

**Closed by lambtho12** 2022-04-27 18:29 UTC
Labels: bug

**Comment by dmytrodubinin** [comment] 2022-04-28 06:20
Thanks

**Comment by volcanoh** [comment] 2024-03-31 06:59
> Just made some tests. It looks like the issue is with filenames with a space in it. Don't do that 😄
> 
> Fixing that now...

It is common for file paths to contain spaces in macOS.
