### ISSUE TITLE
[BUG] show_tags doesn't finish

### ISSUE THREAD

**Issue by zalegrala** [renerocksai/telekasten.nvim#68] opened 2022-01-18 13:22 UTC
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**

```
E5108: Error executing lua .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:493: 'rg --vimgrep -o (^|\s)tags:\s*\[([a-zA-Z]+[a-zA-Z0-9/\-_]*(,\s)*)*] -- /home/zach
/notes' was unable to complete in 5000 ms                                                                                                                                     
stack traceback:                                                                                                                                                              
        [C]: in function 'error'                                                                                                                                              
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:493: in function 'wait'                                                                                   
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:447: in function 'sync'                                                                                   
        ...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:123: in function 'do_find_all_tags'                                                                       
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2391: in function 'selection'                                                                             
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2646: in function 'run_replace_or_original'                                                               
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'                                                                                
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:236: in function 'execute_keymap'                                                                         
        [string ":lua"]:1: in main chunk       
```

Second error.

```
Error executing luv callback:                                                                                                                                                 
...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:68: bad argument #1 to 'sub' (number expected, got nil)                                                           
stack traceback:                                                                                                                                                              
        [C]: in function 'sub'                                                                                                                                                
        ...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:68: in function 'yaml_to_tags'                                                                            
        ...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:97: in function 'parse_entry'                                                                             
        ...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:116: in function '_user_on_exit'                                                                          
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:238: in function '_shutdown'                                                                              
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:45: in function <.../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:36>                          
        [C]: in function 'wait'                                                                                                                                               
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:480: in function 'wait'                                                                                   
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:447: in function 'sync'                                                                                   
        ...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:123: in function 'do_find_all_tags'                                                                       
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2391: in function 'selection'                                                                             
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2646: in function 'run_replace_or_original'                                                               
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'                                                                                
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:236: in function 'execute_keymap'                                                                         
        [string ":lua"]:1: in main chunk                                                                                                                                      
```                                                                                                                               

**To Reproduce**
1. Start nvim
2. `:Telekasten show_tags`
3. See error

**Expected behavior**
This hasn't worked for me, but I would expect to see something other than an error.

**Operating system (please complete the following information):**
 - OS: Linux

**Additional context**

If I copy the `rg` command mentioned in the error (quoting the regex), the command finishes.

**Comment by lambtho12** [comment] 2022-01-18 14:35
Weird, I can not reproduce...

**Comment by zalegrala** [comment] 2022-01-18 15:27
I'm also on Arch.

```
❯ uname -a
Linux flappy 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux
❯ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
❯ rg --version
ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

**Comment by zalegrala** [comment] 2022-01-18 16:30
telekasten (f20fb786)

**Comment by renerocksai** [comment] 2022-01-18 18:04
BTW btw: if you could provide a bit more details about your config that would be much more helpful than just "start nvim", "run command", "error".

Obviously, `show_tags` works on other systems, like mine, so it would be interesting to see where your config or setup might differ to an extent that makes it difficult to grep for tags.

**Comment by renerocksai** [comment] 2022-01-18 18:10
So from the command run I can deduce you're using the weird tag-line in yaml header. I just checked, I cannot reproduce this by just running a tag search.

**Comment by zalegrala** [comment] 2022-01-18 18:50
Sure, I'm using Lunarvim, but I wouldn't expect that to show up here.

Here is my config that started off as the same in the README.

```
local notes = vim.fn.expand("~/notes")
require("telekasten").setup({
	home = notes,
	take_over_my_home = true,
	auto_set_filetype = true,
	dailies = notes .. "/" .. "daily",
	weeklies = notes .. "/" .. "weekly",
	templates = notes .. "/" .. "templates",
	image_subdir = notes .. "/" .. "img",
	extension = ".md",
	follow_creates_nonexisting = true,
	dailies_create_nonexisting = true,
	weeklies_create_nonexisting = true,
	template_new_note = notes .. "/" .. "templates/new_note.md",
	template_new_daily = notes .. "/" .. "templates/daily.md",
	template_new_weekly = notes .. "/" .. "templates/weekly.md",
	image_link_style = "markdown",
	plug_into_calendar = true,
	calendar_opts = {
		weeknm = 4,
		calendar_monday = 1,
		calendar_mark = "left-fit",
	},
	close_after_yanking = false,
	insert_after_inserting = true,
	tag_notation = "yaml-bare",
	command_palette_theme = "ivy",
	show_tags_theme = "ivy",
	subdirs_in_links = true,
	template_handling = "smart",
	new_note_location = "smart",
})
```

I am using the yaml header bits for markdown files.  Not sure how else tags happen, but a few other tools that use this format make this plugin convenient for that use case.

For example:

```
❯ rg --vimgrep -o '(^|\s)tags:\s*\[([a-zA-Z]+[a-zA-Z0-9/\-_]*(,\s)*)*]' -- /home/zach/notes | grep hack
/home/zach/notes/daily/2022-01-08.md:6:1:tags: [vim, hack]
```

**Comment by zalegrala** [comment] 2022-01-18 18:51
The linebreak in the middle could be an artifact of me copying the error from vim.

**Comment by renerocksai** [comment] 2022-01-18 19:03
Thanks for sharing your config. It looks OK!

Unfortunately it seems to be pretty hard to get meaningful errors when an external command fails. I don't know why it should fail but can you try `:lua print(vim.fn.executable("rg"))`? Maybe, for some super weird reason, your nvim cannot find the rg executable.

**Comment by renerocksai** [comment] 2022-01-18 19:04
Alternatively, for further elimination of potential causes, you could temporarily switch the configuration to "#tag" notation...

**Comment by renerocksai** [comment] 2022-01-18 19:15
I have just pushed a change that is supposed to give you more error output (the error message of rg and the return code) - in the hope that it helps finding out what goes wrong. Please try it.

**Comment by zalegrala** [comment] 2022-01-18 20:03
Just tried it, and the error looks the same to me.  `lua print(vim.fn.executable("rg"))` gives me a `1`.

**Comment by renerocksai** [comment] 2022-01-19 06:30
In case of error, you should see a `stderr: ` line (or part of a line if there was no line break in the output). Can you confirm you don't see that. It might be easy to miss.

If you don't get that then the command really never returns and seems to be waiting for input - which is odd. 

So can you tell us what shell you are using? Better, what shell nvim is using? `:lua print(vim.inspect(vim.opt.shell))`. I read on the Lunarvim page that especially the fish shell might be incompatible with external commands.

In addition, let's check scenario#2: for some reason the first error message is crap and we have to look into the second one. What I see immediately is that you don't use whitespace to separate `[ ]` from your tags. Telekasten expects that. If not, at least the trailing `]` will be part the last tag per line. I can fix that (just have) - but that's not our error at hand.

What's interesting is that the regex in question seems to expect a comma in the tag line. I am currently testing if that is the root cause of the problem, together with how the no-comma case is handled.

If everything fails, I recommend switching to "#tag" notation within your `tags:` line and as `tag_notation`. Yaml-bare is a 2nd-class citizen at the moment anyway, since selecting a tag will launch a "live grep" with that tag - which works fine for both `#tag` and `:tag:` as such "words" usually don't occur in plain text. This search is not confined to yaml blocks, though,  so it might be kind of useless at the moment. This could be changed since the tag-search already produces everything telescope needs to know: file, line, column number of the occurrence of a tag. But implementing this would need some work, especially to repeat the search when user input changes - which can lead to a bit of a callback hell. 


Have you tried any of the other things I suggested (changing your tag_notation setting, for example)?

**Comment by renerocksai** [comment] 2022-01-19 06:36
It was the `tags: [single_tag]`. Fixed.

**Closed** 2022-01-19 06:36 UTC
Labels: bug, feedback needed

**Comment by zalegrala** [comment] 2022-01-19 13:07
Oh nice, thanks for the support!

**Comment by dietrich** [comment] 2022-03-15 23:11
I have the same exact issue and outcome error as above but with tag_notation ="#tag". If I switch to ":tag:" and then write a tag... it works.
