### ISSUE TITLE
It seems that telekasten is not working properly on windows.

### ISSUE THREAD

**Issue by ok97465** [renerocksai/telekasten.nvim#60] opened 2022-01-07 11:59 UTC
Hello.
I am a big fan of telekasten.
Thank you for your great work.

I tried to use telekasten on windows 10 with nvim 0.6.1.
Link address is long when executing insert link command.
![1](https://user-images.githubusercontent.com/22970578/148540156-fb590f3d-7b4f-40d1-96f6-999eb5d314de.gif)

An error occurs when executing follow link command.
![2](https://user-images.githubusercontent.com/22970578/148540162-a052dd48-b7e5-4ac8-837f-0bfbeb124778.gif)

The configuration file I used is as follows.
```vim
syntax on 
filetype on
let mapleader=" "

set nocompatible    

call plug#begin('~/.vim/plugged')

Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'renerocksai/calendar-vim'
Plug 'renerocksai/telekasten.nvim'

call plug#end()

" ----- telekasten -----
lua << EOF
local home = vim.fn.expand("c:/schedule")
require('telekasten').setup({
    home         = home,

    -- if true, telekasten will be enabled when opening a note within the configured home
    take_over_my_home = true,

    -- auto-set telekasten filetype: if false, the telekasten filetype will not be used
    --                               and thus the telekasten syntax will not be loaded either
    auto_set_filetype = true,

    dailies      = home .. '/' .. 'daily',
    weeklies     = home .. '/' .. 'weekly',
    templates    = home .. '/' .. 'templates',

    -- image subdir for pasting
    -- subdir name
    -- or nil if pasted images shouldn't go into a special subdir
    image_subdir = "img",

    -- markdown file extension
    extension    = ".md",

    -- following a link to a non-existing note will create it
    follow_creates_nonexisting = true,
    dailies_create_nonexisting = true,
    weeklies_create_nonexisting = true,

    -- template for new notes (new_note, follow_link)
    -- set to `nil` or do not specify if you do not want a template
    template_new_note = home .. '/' .. 'templates/new_note.md',

    -- template for newly created daily notes (goto_today)
    -- set to `nil` or do not specify if you do not want a template
    template_new_daily = home .. '/' .. 'templates/daily.md',

    -- template for newly created weekly notes (goto_thisweek)
    -- set to `nil` or do not specify if you do not want a template
    template_new_weekly= home .. '/' .. 'templates/weekly.md',

    -- image link style
    -- wiki:     ![[image name]]
    -- markdown: ![](image_subdir/xxxxx.png)
    image_link_style = "markdown",

    -- integrate with calendar-vim
    plug_into_calendar = true,
    calendar_opts = {
        -- calendar week display mode: 1 .. 'WK01', 2 .. 'WK 1', 3 .. 'KW01', 4 .. 'KW 1', 5 .. '1'
        weeknm = 4,
        -- use monday as first day of week: 1 .. true, 0 .. false
        calendar_monday = 1,
        calendar_diary = home .. '/diary',

        -- calendar mark: where to put mark for marked days: 'left', 'right', 'left-fit'
        calendar_mark = 'left-fit',
    },

    -- telescope actions behavior
    close_after_yanking = false,
    insert_after_inserting = true,

    -- tag notation: '#tag', ':tag:', 'yaml-bare'
    tag_notation = "#tag",

    -- command palette theme: dropdown (window) or ivy (bottom panel)
    command_palette_theme = "ivy",

    -- tag list theme:
    -- get_cursor: small tag list at cursor; ivy and dropdown like above
    show_tags_theme = "ivy",

    -- when linking to a note in subdir/, create a [[subdir/title]] link
    -- instead of a [[title only]] link
    subdirs_in_links = true,

    -- template_handling
    -- What to do when creating a new note via `new_note()` or `follow_link()`
    -- to a non-existing note
    -- - prefer_new_note: use `new_note` template
    -- - smart: if day or week is detected in title, use daily / weekly templates (default)
    -- - always_ask: always ask before creating a note
    template_handling = "smart",

    -- path handling:
    --   this applies to:
    --     - new_note()
    --     - new_templated_note()
    --     - follow_link() to non-existing note
    --
    --   it does NOT apply to:
    --     - goto_today()
    --     - goto_thisweek()
    --
    --   Valid options:
    --     - smart: put daily-looking notes in daily, weekly-looking ones in weekly,
    --              all other ones in home, except for notes/with/subdirs/in/title.
    --              (default)
    --
    --     - prefer_home: put all notes in home except for goto_today(), goto_thisweek()
    --                    except for notes with subdirs/in/title.
    --
    --     - same_as_current: put all new notes in the dir of the current note if
    --                        present or else in home
    --                        except for notes/with/subdirs/in/title.
    new_note_location = "smart",

})
EOF

```

**Comment by lambtho12** [comment] 2022-01-08 17:09
I am not an expert when it comes to windows, but I guess for point 1 the issue has more to do with Telescope itself than Telekasten, no? When you try to simply open a file using Telescope, do you see the whole path as well? If not, then Telekasten needs to properly parse windows paths (in the telescope picker, and when it pastes them).

For the second point, it is a bit strange and there are multiple issues.
1. Telekasten thinks the link is not an internal file and assumes it is an URL. This is because the link is malformed due to the first issue. If you put `[daily/2022-01-12.md] ` and try to open that, I think it would work as expected.
2. In any case, it should gracefully throws an error and refuse to open the URL and not crash (see code excerpt below). I guess it detects your OS as unix for some reason. IMO, this is likely because of your setup (how are you using nvim with windows exactly? What shell?).
 
https://github.com/renerocksai/telekasten.nvim/blob/90f9cd784b2983ecc2469716fd36dc17e45fe785/lua/telekasten.lua#L1150-L1159

**Comment by renerocksai** [comment] 2022-01-16 07:55
I second @lambtho12's points. 

1. It appears that Telescope is fine with weird `C:#a#b#c.md` paths or else the finder wouldn't work. Unfortunately, with paths like that, splitting them (by `\` on windows, done by plenary) doesn't work, which makes it impossible to just insert the file name. Hence, you end up with weird names in the `[[link]]`.
2. These weird links containing drive letter and colon confuse Telekasten. Its very simple check whether something is a filename without extension (`YYYY-MM-DD`) or an URL is done simply by checking for a colon - because it shouldn't care about the protocol. Now that I think of it, a check for `://` would be better. Maybe the weird paths will, while remaining ugly, work with `follow_link()` then.
3. Your setup makes nvim believe it's Unix when it's clearly not.

I can also see that you seem to be in a conda environment `base`. Maybe `conda deactivate` will make a difference - at least no conda libs will interfere. Though I doubt it. Looking at your prompt, it also contains `C#schedule`, which I find highly suspicious.

Unfortunately, I don't have a Windows machine to try things out myself. I am somewhat doubtful I'd hit the same issues as you since this `C:#` business is something I haven't seen on Windows before.

One thing I'd suggest is activating / installing WSL2 and try nvim within that. That _should_ give you the closest thing to Linux that's possible on Windows without running a VM.

However, I'll check out the colon = link business and mayyybe that might bring some mild relief.

**Comment by renerocksai** [comment] 2022-01-16 08:38
I have to correct myself. There is no colon = tag (anymore). What happens now is: 

telekasten tries to find out if you are in a link or a tag that you want to follow. It starts searching at your cursor position and goes backwards. When it sees a `#`, it thinks it found a tag, because of your `tag_notation`. But this doesn't seem to be the case. When it sees a `:`, it would assume it's in a tag, provided `tag_notation` were `":tag:"`. This also isn't the case. It eventually arrives at `[` and correctly assumes, this is a link. Now it should go on and figure out how to open the link.

But nothing like this happens, because you invoke `Telekasten follow_link` in line `6`, column `8`, at the end of `- [ ] yy`.

![2022-01-16_09-27](https://user-images.githubusercontent.com/30892199/149652807-d7c3c753-5aa7-41da-b513-f806ba5b7f45.png)

If I do this, telekasten just ignores the command because it cannot find a link or tag in the current line. This should happen in your example, too. 

In your case, however, it tries to open a URL. This is suspicious!
![image](https://user-images.githubusercontent.com/30892199/149652913-9ad96235-043e-453e-9a53-9f181fd02598.png)

I cannot investigate furhter because you seem to run a pretty old version of telekasten. Please try `:PlugUpdate` or `:PlugUpdate telekasten.nvim`.

Your version must be so old that it uses `yi]` to find out the contents of the link which is highly unreliable when your cursor is outside of a link, which it is in your case (line 6, column 8).

Please update telekasten and try again.

**Comment by ok97465** [comment] 2022-01-16 14:22
> I cannot investigate further because you seem to run a pretty old version of telekasten, as is evident by the presence of `run_replace_or_original` which doesn't exist in the current codebase. Please try `:PlugUpdate` or `:PlugUpdate telekasten.nvim`.

I updated telekasten to f20fb78. But the error is similar to before.

![image](https://user-images.githubusercontent.com/22970578/149663748-4ad29499-29cb-4f02-9826-8286b0ab292d.png)

The traceback of nvim is weird. "run_replace_original" is in  "telescope/actions/mt.lua:30"

And I can't use WSL at our company. So I tried to use telekasten in windows. But it's not easy. 😅 

Anyway, thank you for your answer.

**Comment by Rom1deTroyes** [comment] 2022-01-16 19:47
> I can't use WSL at our company.

Maybe GitBash can be of any help : it includes basic unix tools (ls, sort, ...), and has a «Portable» version that don't need to be installed. The SDK version also includes pacman as package manager : 
https://gitforwindows.org/

I have a Windows 11 with WSL2 at wokr, so I will try to test this in the week :-)

**Comment by renerocksai** [comment] 2022-01-17 08:31
> > I cannot investigate further because you seem to run a pretty old version of telekasten, as is evident by the presence of `run_replace_or_original` which doesn't exist in the current codebase. Please try `:PlugUpdate` or `:PlugUpdate telekasten.nvim`.
> 
> I updated telekasten to [f20fb78](https://github.com/renerocksai/telekasten.nvim/commit/f20fb7862b35be4795ad76ed08d1011f94f59d0b). But the error is similar to before.
> 
> ![image](https://user-images.githubusercontent.com/22970578/149663748-4ad29499-29cb-4f02-9826-8286b0ab292d.png)
> 
> The traceback of nvim is weird. "run_replace_original" is in "telescope/actions/mt.lua:30"
> 
> And I can't use WSL at our company. So I tried to use telekasten in windows. But it's not easy. sweat_smile

Yeah, Windows is definitely NOT an OS of choice. Alternatives to running WSL2 could be:

-  a VM 
- or maybe easier: Docker
- GitBash 
- cygwin (but I read nvim supposedly cut support for cygwin ages ago)

In any case, NOT using the windows CMD prompt is highly recommended. Alternatives may be

- Cmder which supposedly ships with Git for Windows
- the new Windows terminal

I also read that a superior Windows experience is achieved by running "Neovim Qt" or "fvim". Google is your friend here.

- nvim-qt is contained in the downloadable nvim Windows releases.

> Anyway, thank you for your answer.

Your traceback is weird, indeed! `selection()` is called in line 2646, yet is reported as being in line 1235. In line 1235 is the call to xdg-open. So something really weird is going on here.

However, `selection()` is only called when you use the "command palette": the telescope picker where you can select a telekasten command. 

- Have you ever tried typing `:Telekasten follow_link` - instead of using the command picker?
  - maybe that would give a more helpful error showing where in the function an error happens
- Have you tried placing the cursor inside the link (at what position?) when running `follow_link`?

Anyway, until we get more information about what's really happening, there's not too much we can do here. If I had a Win machine handy I'd try some stuff, provided I can reproduce what you're encountering.

If you're brave, you can hack telekasten.nvim: Around line 1785 you should find the `local function FollowLink(opts)`.

Insert lines like `print("1")`, `print("2")` in there to see how far it gets, starting from the top of the function. That way you'll find out exactly what breaks - and maybe we can take it from there. If you're curious, you can always `print(vim.inspect(some_variable_name))` - to see what's in there. Maybe that will give you (or us) an idea...

**Comment by renerocksai** [comment] 2022-01-17 08:34
Update: `:lua require('telekasten').follow_link()` would be even better than `:Telekasten follow_link` since it has to go through less indirections.

**Comment by renerocksai** [comment] 2022-01-20 09:21
My advice: replace `c:/schedule` with `/schedule`.

Closing for now. Please re-open or comment if problems persist.

**Closed by renerocksai** 2022-01-20 09:21 UTC
Labels: feedback needed

**Comment by yantongl** [comment] 2022-05-25 09:23
@ok97465 what shell program were you using? Also, what language do you use on your machine? I noticed that it uses # to represent '\\' in the path before entering nvim. It is super strange and I suspect it is a system (or the shell app) path representation issue

**Comment by ok97465** [comment] 2022-05-25 09:46
> 

Thanks for reply. I usually use basic "cmd". My machine language is Korean. 
I don't know if this problem still exists.
I am using my own telekasten version by modifying the lua code.

**Comment by yantongl** [comment] 2022-05-27 05:58
I have tried several times in the past two days with cmd.exe. It is working fine with me if I only use English characters for zettel names, no matter where my cwd is, even when the cwd contains Chinese characters. However, when I tried to create a zettel whose name contains Chinese characters, it started to fail to work. I think telekasten might not handle Unicode characters in its path properly. From your video, you do have a strange unicode character representing the '\' path separator. I still suspect that is what caused the problem.

**Comment by lambtho12** [comment] 2022-05-27 07:14
Indeed, TK does not work well with non latin characters. Mainly due to the different regex used. See https://github.com/renerocksai/telekasten.nvim/issues/135

But the path thing is something entirely different. It is already painful enough to accommodate the "normal" (`:\\` and  `\`) windows type of paths. So if people start using other chars there is nothing really we can do.
I think TK should rely as much as possible on Pleanry.Path for path manipulation (this is already what is done for the most part).
