### ISSUE TITLE
[BUG] insert_link doesn't work

### ISSUE THREAD

**Issue by dmytrodubinin** [renerocksai/telekasten.nvim#186] opened 2022-11-23 11:47 UTC
**Please confirm**
I am running the latest version of this plugin

**Describe the bug**
I created screencast. You can see that I try to insert link inside note, but it only open new note
[Screencast from 2022-11-23 13-42-44.webm](https://user-images.githubusercontent.com/8066458/203539129-6fe6b05e-f01d-4b16-afd4-16a6cb3a5a04.webm)

**Operating system (please complete the following information):**
 - OS: Fedora 37

**Comment by lambtho12** [comment] 2022-11-23 12:29
I just tested on my setup, I cannot reproduce. It works as expected, in all modes; with and without the option `{i=true}`.

Can someone else try to reproduce as well?

**Comment by dmytrodubinin** [comment] 2022-11-25 19:14
I found the reason. In telescope.lua I have settings to edit tab is file already opened:
```
        ["<cr>"] = function(bufnr)
               require("telescope.actions.set").edit(bufnr, "tab drop")
        end,

```
If I comment this, isert_link works. But I need this setting in my config. How to fix this?

**Comment by lambtho12** [comment] 2022-11-26 10:59
There is not real way around here. (I think). If you redefine telescope actions globally, then it will impact all pickers. 
I am not sure we want to redefine them specifically for telekasten. This may annoy people that want their global remap for actions to work a certain way... Besides, I am currently very busy with work and do not have time to craft an ad-hoc solution for such a niche issue.

Here are two workarounds that seem reasonable to me instead:

1. Are you sure you absolutely need to set that in your config? Usually the <CR> default action is already doing what you want most of the time anyway, no? If you really need that, maybe reconsider mapping `<C-CR>` or `<S-CR>` instead of `<CR`> for this function. This will keep the default `<CR>` and ensure telekasten (and other packages) proper working.
2. An other option is to use the `<C-i>` action in telekasten. This works in all telekasten pickers and will paste the link to the file currently highlighted. So if you have not remaped that in your telescope config, you can use any telekasten function (insert_link or even find_file) and press `<C-i>` to paste the link.

Does any of this work for you? If yes, do not hesitate to close this issue.

**Comment by dmytrodubinin** [comment] 2022-11-26 15:03
>     2. An other option is to use the `<C-i>` action in telekasten. This works in all telekasten pickers and will paste the link to the file currently highlighted. So if you have not remaped that in your telescope config, you can use any telekasten function (insert_link or even find_file) and press `<C-i>` to paste the link.

Oh, thanks! `<C-i>` works well. That what I need!
And Yes, I need my configuration in telescope. I even asked on reddit how to do it.

**Closed** 2022-11-26 15:03 UTC
Labels: bug
